blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [

    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view', ),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update', ),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete', ),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sender.urls', namespace='mailsender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sender/urls.py
from django.urls import path

from sender import views as my_view
from sender.apps import MailSenderConfig

app_name = MailSenderConfig.name

urlpatterns = [

    path('', my_view.home, name='home'),

    path('customers', my_view.CustomersView.as_view(), name='all_customers'),
    path('customer/<int:pk>', my_view.CustomerDetailView.as_view(), name='customer'),
    path('customer/create', my_view.CustomerCreateView.as_view(), name='customer_create'),
    path('customer/update/<int:pk>', my_view.CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/delete/<int:pk>', my_view.CustomerDeleteView.as_view(), name='customer_delete'),

    path('email-templates', my_view.ContentEmailView.as_view(), name='all_email_templates'),
    path('email-template/<int:pk>', my_view.ContentEmailDetailView.as_view(), name='email_template'),
    path('email-template/create', my_view.ContentEmailCreateView.as_view(), name='email_template_create'),
    path('email-template/update/<int:pk>', my_view.ContentEmailUpdateView.as_view(), name='email_template_update'),
    path('email-template/delete/<int:pk>', my_view.ContentEmailDeleteView.as_view(), name='email_template_delete'),

    path('email-settings', my_view.SetEmailingView.as_view(), name='all_emailing'),
    path('email-setting/<int:pk>', my_view.SetEmailingDetailView.as_view(), name='email_setting'),
    path('email-setting/create', my_view.SetEmailingCreateView.as_view(), name='email_setting_create'),
    path('email-setting/update/<int:pk>', my_view.SetEmailingUpdateView.as_view(), name='email_setting_update'),
    path('email-setting/delete/<int:pk>', my_view.SetEmailingDeleteView.as_view(), name='email_setting_delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, wait_confirm_email, ConfirmPage, UserForgotPasswordView, \
     UserPasswordResetDoneView, UserPasswordResetConfirmView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('wait-confirm-email/', wait_confirm_email, name='confirm_email'),
    path('confirm_email/<int:pk>', ConfirmPage.as_view(), name='confirmed_email'),
    path('password-reset/', UserForgotPasswordView.as_view(), name='password_reset'),
    path('set-new-password/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-sent/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

sender/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}

CHOICES_STATUS = (
    ('CR', 'Created'),
    ('IP', 'In Progress'),
    ('CL', 'Closed'),
)

FREQUENCY_SEND = (
    ('OD', 'Once a day'),
    ('OW', 'Once a week'),
    ('OM', 'Once a month'),
)


class Customer(models.Model):
    email = models.CharField(max_length=150, verbose_name='e-mail')
    full_name = models.CharField(max_length=150, verbose_name='фио', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    is_blocked = models.BooleanField(default=False, verbose_name='заблокирован')

    def delete(self, *args, **kwargs):
        self.is_blocked = True
        self.save()

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'получатель'
        verbose_name_plural = 'получатели'


class ContentEmail(models.Model):
    headliner = models.CharField(max_length=150, verbose_name='тема письма')
    text = models.TextField(verbose_name='текст письма')
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Добавлено', **NULLABLE)

    def __str__(self):
        return f'{self.headliner}'

    class Meta:
        verbose_name = 'письмо для рассылки'
        verbose_name_plural = 'письма для рассылки'


class SendSettings(models.Model):

    name = models.CharField(max_length=150, verbose_name='название рассылки')
    send_time = models.TimeField(verbose_name='Время отправки')
    period = models.CharField(max_length=2, choices=FREQUENCY_SEND, default='OM', verbose_name='Частота рассылки')
    status = models.CharField(max_length=2, choices=CHOICES_STATUS, default='CR', verbose_name='Статус')
    message = models.ForeignKey(ContentEmail, on_delete=models.CASCADE, verbose_name='Текст рассылки', **NULLABLE)
    customer = models.ManyToManyField(Customer, verbose_name='Клиенты', **NULLABLE)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Добавлено', **NULLABLE)

    def delete(self, *args, **kwargs):
        self.status = 'CL'
        self.save()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'настройка рассылки'
        verbose_name_plural = 'настройки рассылок'


class EmailLogs(models.Model):
    data_last_sent = models.DateTimeField(verbose_name='дата последней рассылки')
    status_issue = models.BooleanField(default=False, verbose_name='статус попытки')
    server_respond = models.CharField(max_length=50, verbose_name='ответ сервера', **NULLABLE)
    sender = models.ForeignKey(SendSettings, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.server_respond}'

sender/forms.py
from django import forms
from sender.models import Customer, ContentEmail, SendSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class CustomerForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'


class WriteEmailForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = ContentEmail
        exclude = ('created_by',)


class SendSettingsForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = SendSettings
        exclude = ('status', 'created_by',)

sender/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from sender import models as my_models
from sender import forms as my_forms
from blog.models import Blog
from sender.services import get_cache


def home(request):
    customers = my_models.Customer.objects.all()
    settings = my_models.SendSettings.objects.all()
    act_settings = my_models.SendSettings.objects.filter(status='CR')
    blog_posts = Blog.objects.filter(is_published=True)
    blog_posts_random = blog_posts.order_by('?')[:3]
    context = {
        'customers': customers,
        'settings': settings,
        'act_settings': act_settings,
        'blog_posts': blog_posts,
        'blog_posts_random': get_cache('posts', blog_posts_random),
        'title': 'Главная'
    }
    return render(request, 'sender/home.html', context)


class CheckPermEditMixin:
    """Mixin для проверки владельца или суперпользователя"""
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user and not self.request.user.is_superuser:
            raise Http404('Недостаточно прав доступа - только владелец может редактировать эту страницу')
        return self.object


class CustomersView(LoginRequiredMixin, generic.ListView):
    model = my_models.Customer
    extra_context = {
        'title': 'Получатели'
    }

    def get_queryset(self, *args, **kwargs):
        """выборка активных пользователей из всех"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_blocked=False)
        return queryset


class CustomerDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.Customer

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class CustomerCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.Customer
    form_class = my_forms.CustomerForm
    success_url = reverse_lazy('mailsender:all_customers')


class CustomerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = my_models.Customer
    form_class = my_forms.CustomerForm
    success_url = reverse_lazy('mailsender:all_customers')


class CustomerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.Customer
    success_url = reverse_lazy('mailsender:all_customers')
    extra_context = {
        'title': 'Удалить получателя'
    }


class ContentEmailView(LoginRequiredMixin, generic.ListView):
    model = my_models.ContentEmail
    extra_context = {
        'title': 'Шаблоны писем'
    }


class ContentEmailDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.ContentEmail

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ContentEmailCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.ContentEmail
    form_class = my_forms.WriteEmailForm
    success_url = reverse_lazy('mailsender:all_email_templates')

    def form_valid(self, form):
        """заполнение поля владельца при валидации формы"""
        if form.is_valid():
            fields = form.save(commit=False)
            fields.created_by = self.request.user
        return super().form_valid(form)


class ContentEmailUpdateView(LoginRequiredMixin, CheckPermEditMixin, generic.UpdateView):
    model = my_models.ContentEmail
    form_class = my_forms.WriteEmailForm
    success_url = reverse_lazy('mailsender:all_email_templates')


class ContentEmailDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.ContentEmail
    success_url = reverse_lazy('mailsender:all_email_templates')
    extra_context = {
        'title': 'Удалить шаблон письма'
    }


class SetEmailingView(LoginRequiredMixin, generic.ListView):
    model = my_models.SendSettings
    extra_context = {
        'title': 'Настройки рассылок'
    }


class SetEmailingDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.SendSettings

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class SetEmailingCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.SendSettings
    form_class = my_forms.SendSettingsForm
    success_url = reverse_lazy('mailsender:all_emailing')

    def form_valid(self, form):
        """заполнение поля владельца при валидации формы"""
        if form.is_valid():
            fields = form.save(commit=False)
            fields.created_by = self.request.user
        return super().form_valid(form)


class SetEmailingUpdateView(LoginRequiredMixin, CheckPermEditMixin, generic.UpdateView):
    model = my_models.SendSettings
    form_class = my_forms.SendSettingsForm
    success_url = reverse_lazy('mailsender:all_emailing')


class SetEmailingDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.SendSettings
    success_url = reverse_lazy('mailsender:all_emailing')
    extra_context = {
        'title': 'Удалить настройки рассылки'
    }

sender/templates/sender/includes/incl_bottom_menu.html
<div class="col-6 col-md">
            <h5></h5>

          </div>
          <div class="col-6 col-md">
            <h5></h5>

          </div>
          <div class="col-6 col-md">
            <h5></h5>

          </div>

sender/templates/sender/includes/sidebar.html
    <div class="sidebar d-flex flex-column align-items-start justify-content-between">
        <a href="/" class="d-flex align-items-center mb-3 text-white text-decoration-none">
            <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4">Меню</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <li class="nav-item">
                <a href="/" class="nav-link active" aria-current="page">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                    Главная
                </a>
            </li>
            <li>
                <a href="{% url 'mailsender:all_customers' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                    Клиенты
                </a>
            </li>
            <li>
                <a href="{% url 'mailsender:all_emailing' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
                    Рассылки
                </a>
            </li>
             <li>
                <a href="{% url 'mailsender:all_email_templates' %}" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                    Шаблоны
                </a>
            </li>
            <li>
                <a href="/blog" class="nav-link text-white">
                    <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                    Блог
                </a>
            </li>
        </ul>
        <hr>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
               data-bs-toggle="dropdown" aria-expanded="false">
                <img src="
                {% if user.avatar %}
                    {{ user.avatar.url }}
                    {% else %}

                    {% endif %}
                         " alt="" width="32" height="32" class="rounded-circle me-2">
                <strong>
                    {% if user.is_authenticated %}
                    {{ user.first_name }}
                    {% else %}
                    Пользователь
                    {% endif %}

                </strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Редактировать профиль</a></li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}
            </ul>
        </div>
    </div>