blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [

    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view', ),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update', ),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete', ),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sender.urls', namespace='mailsender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from slugify import slugify

from django.db import models
from users.models import User, NULLABLE


class Blog(models.Model):
    title_name = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Текст', **NULLABLE)
    preview = models.ImageField(upload_to='blog/preview', default='preview/default.JPG', verbose_name='Изображение')
    data_creating = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    autor = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор')

    def __str__(self):
        return f'{self.title_name}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блог'

blog/forms.py
from django import forms
from blog.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class BlogForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('title_name', 'content', 'preview', )

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic


from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(generic.ListView):
    model = Blog
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        queryset = queryset.order_by('-data_creating')
        return queryset


class BlogDetailView(generic.DetailView):
    model = Blog


class BlogCreateView(LoginRequiredMixin, generic.CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Написать статью'
    }

    def form_valid(self, form):
        if form.is_valid():
            fields = form.save(commit=False)
            fields.autor = self.request.user
            fields.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Редактировать статью'
    }


class BlogDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Удалить статью'
    }

blog/templates/blog/blog_confirm_delete.html
{% extends 'sender/base.html' %}
  {% block content %}

        <div class="container">

                <div class="">
                    <form method="post">
                        {% csrf_token %}

                        <h3>Вы уверены что хотите удалить статью "{{ object }}"?</h3>
                            <input type="submit" class="btn btn-lg btn-outline-danger" value="Удалить">
                            <a href="{% url 'blog:blog' %}" type="button" class="btn btn-lg btn-outline-warning">Вернуться</a>
                    </form>

                </div>

        </div>

        {% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'sender/base.html' %}

  {% block content %}

      <div class="container">

          <div class="card-deck mb-3 text-center">

            <div class="card mb-4 box-shadow">

              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.title_name }}</h4>
              </div>

              <div class="card-body">

                {% if object.preview %}
                  <div><img src='{{object.preview.url }}' align="left" width="100%" height="100%"></div>
                  {% else %}}
                  <div><img src="/preview/default.JPG" align="left" width="100%" height="100%"></div>
                {% endif %}
                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ object.content }}</li>

                </ul>


                <p><b>Дата создания:</b> {{ object.data_creating }}</p>

                <a href="{% url 'blog:blog_list' %}" type="button" class="btn btn-lg btn-block btn-outline-warning">Вернуться</a>
              </div>

            </div>

          </div>

      </div>
  {% endblock %}

blog/templates/blog/blog_form.html
{% extends 'sender/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Добавить статью в блог</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Блог</h1>
      <p class="lead">Список статей в блоге</p>
    </div>


      <div class="container">
        <a href="{% url 'blog:blog_create' %}" class="btn btn-lg btn-outline-primary">Создать статью</a>
        <p></p>
{% for post in object_list%}
          <div class="card-deck mb-3 text-center">

            <div class="card mb-10 box-shadow">

              <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ post.title_name }}</h4>
              </div>

              <div class="card-body">



                <p class="card-text">
                  <b>Дата публикации:</b> {{ post.data_creating }}
                </p>
                {% if post.preview %}
                  <div><img src='{{ post.preview.url }}'  align="left" width="100%" height="100%"></div>
                {% else %}
                  <div><img src="/media/preview/default.JPG" align="center"></div>
                {% endif %}

                <ul class="list-unstyled mt-3 mb-4">
                  <li>{{ post.content  | slice:"0:100"}}</li>

                </ul>
                <a href="{% url 'blog:blog_view' post.pk %}" type="button" class="btn btn-lg btn-block btn-outline-dark" >Читать статью</a>
                <a href="{% url 'blog:blog_update' post.pk  %}" type="button" class="btn btn-lg btn-block btn-outline-warning">Редактировать статью</a>
                <a href="{% url 'blog:blog_delete' post.pk  %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить статью</a>

              </div>
              <p></p>

            </div>

          </div>
{% endfor %}
      </div>
  {% endblock %}