blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [

    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view', ),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update', ),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete', ),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sender.urls', namespace='mailsender')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sender/urls.py
from django.urls import path

from sender import views as my_view
from sender.apps import MailSenderConfig

app_name = MailSenderConfig.name

urlpatterns = [

    path('', my_view.home, name='home'),

    path('customers', my_view.CustomersView.as_view(), name='all_customers'),
    path('customer/<int:pk>', my_view.CustomerDetailView.as_view(), name='customer'),
    path('customer/create', my_view.CustomerCreateView.as_view(), name='customer_create'),
    path('customer/update/<int:pk>', my_view.CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/delete/<int:pk>', my_view.CustomerDeleteView.as_view(), name='customer_delete'),

    path('email-templates', my_view.ContentEmailView.as_view(), name='all_email_templates'),
    path('email-template/<int:pk>', my_view.ContentEmailDetailView.as_view(), name='email_template'),
    path('email-template/create', my_view.ContentEmailCreateView.as_view(), name='email_template_create'),
    path('email-template/update/<int:pk>', my_view.ContentEmailUpdateView.as_view(), name='email_template_update'),
    path('email-template/delete/<int:pk>', my_view.ContentEmailDeleteView.as_view(), name='email_template_delete'),

    path('email-settings', my_view.SetEmailingView.as_view(), name='all_emailing'),
    path('email-setting/<int:pk>', my_view.SetEmailingDetailView.as_view(), name='email_setting'),
    path('email-setting/create', my_view.SetEmailingCreateView.as_view(), name='email_setting_create'),
    path('email-setting/update/<int:pk>', my_view.SetEmailingUpdateView.as_view(), name='email_setting_update'),
    path('email-setting/delete/<int:pk>', my_view.SetEmailingDeleteView.as_view(), name='email_setting_delete'),

]

sender/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}

CHOICES_STATUS = (
    ('CR', 'Created'),
    ('IP', 'In Progress'),
    ('CL', 'Closed'),
)

FREQUENCY_SEND = (
    ('OD', 'Once a day'),
    ('OW', 'Once a week'),
    ('OM', 'Once a month'),
)


class Customer(models.Model):
    email = models.CharField(max_length=150, verbose_name='e-mail')
    full_name = models.CharField(max_length=150, verbose_name='фио', **NULLABLE)
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)
    is_blocked = models.BooleanField(default=False, verbose_name='заблокирован')

    def delete(self, *args, **kwargs):
        self.is_blocked = True
        self.save()

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'получатель'
        verbose_name_plural = 'получатели'


class ContentEmail(models.Model):
    headliner = models.CharField(max_length=150, verbose_name='тема письма')
    text = models.TextField(verbose_name='текст письма')
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Добавлено', **NULLABLE)

    def __str__(self):
        return f'{self.headliner}'

    class Meta:
        verbose_name = 'письмо для рассылки'
        verbose_name_plural = 'письма для рассылки'


class SendSettings(models.Model):

    name = models.CharField(max_length=150, verbose_name='название рассылки')
    send_time = models.TimeField(verbose_name='Время отправки')
    period = models.CharField(max_length=2, choices=FREQUENCY_SEND, default='OM', verbose_name='Частота рассылки')
    status = models.CharField(max_length=2, choices=CHOICES_STATUS, default='CR', verbose_name='Статус')
    message = models.ForeignKey(ContentEmail, on_delete=models.CASCADE, verbose_name='Текст рассылки', **NULLABLE)
    customer = models.ManyToManyField(Customer, verbose_name='Клиенты', **NULLABLE)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Добавлено', **NULLABLE)

    def delete(self, *args, **kwargs):
        self.status = 'CL'
        self.save()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'настройка рассылки'
        verbose_name_plural = 'настройки рассылок'


class EmailLogs(models.Model):
    data_last_sent = models.DateTimeField(verbose_name='дата последней рассылки')
    status_issue = models.BooleanField(default=False, verbose_name='статус попытки')
    server_respond = models.CharField(max_length=50, verbose_name='ответ сервера', **NULLABLE)
    sender = models.ForeignKey(SendSettings, on_delete=models.SET_NULL, **NULLABLE)

    def __str__(self):
        return f'{self.server_respond}'

sender/forms.py
from django import forms
from sender.models import Customer, ContentEmail, SendSettings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'autocomplete': 'off'
            })


class CustomerForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'


class WriteEmailForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = ContentEmail
        exclude = ('created_by',)


class SendSettingsForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = SendSettings
        exclude = ('status', 'created_by',)

sender/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from sender import models as my_models
from sender import forms as my_forms
from blog.models import Blog
from sender.services import get_cache


def home(request):
    customers = my_models.Customer.objects.all()
    settings = my_models.SendSettings.objects.all()
    act_settings = my_models.SendSettings.objects.filter(status='CR')
    blog_posts = Blog.objects.filter(is_published=True)
    blog_posts_random = blog_posts.order_by('?')[:3]
    context = {
        'customers': customers,
        'settings': settings,
        'act_settings': act_settings,
        'blog_posts': blog_posts,
        'blog_posts_random': get_cache('posts', blog_posts_random),
        'title': 'Главная'
    }
    return render(request, 'sender/home.html', context)


class CheckPermEditMixin:
    """Mixin для проверки владельца или суперпользователя"""
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user and not self.request.user.is_superuser:
            raise Http404('Недостаточно прав доступа - только владелец может редактировать эту страницу')
        return self.object


class CustomersView(LoginRequiredMixin, generic.ListView):
    model = my_models.Customer
    extra_context = {
        'title': 'Получатели'
    }

    def get_queryset(self, *args, **kwargs):
        """выборка активных пользователей из всех"""
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_blocked=False)
        return queryset


class CustomerDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.Customer

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class CustomerCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.Customer
    form_class = my_forms.CustomerForm
    success_url = reverse_lazy('mailsender:all_customers')


class CustomerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = my_models.Customer
    form_class = my_forms.CustomerForm
    success_url = reverse_lazy('mailsender:all_customers')


class CustomerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.Customer
    success_url = reverse_lazy('mailsender:all_customers')
    extra_context = {
        'title': 'Удалить получателя'
    }


class ContentEmailView(LoginRequiredMixin, generic.ListView):
    model = my_models.ContentEmail
    extra_context = {
        'title': 'Шаблоны писем'
    }


class ContentEmailDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.ContentEmail

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ContentEmailCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.ContentEmail
    form_class = my_forms.WriteEmailForm
    success_url = reverse_lazy('mailsender:all_email_templates')

    def form_valid(self, form):
        """заполнение поля владельца при валидации формы"""
        if form.is_valid():
            fields = form.save(commit=False)
            fields.created_by = self.request.user
        return super().form_valid(form)


class ContentEmailUpdateView(LoginRequiredMixin, CheckPermEditMixin, generic.UpdateView):
    model = my_models.ContentEmail
    form_class = my_forms.WriteEmailForm
    success_url = reverse_lazy('mailsender:all_email_templates')


class ContentEmailDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.ContentEmail
    success_url = reverse_lazy('mailsender:all_email_templates')
    extra_context = {
        'title': 'Удалить шаблон письма'
    }


class SetEmailingView(LoginRequiredMixin, generic.ListView):
    model = my_models.SendSettings
    extra_context = {
        'title': 'Настройки рассылок'
    }


class SetEmailingDetailView(LoginRequiredMixin, generic.DetailView):
    model = my_models.SendSettings

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class SetEmailingCreateView(LoginRequiredMixin, generic.CreateView):
    model = my_models.SendSettings
    form_class = my_forms.SendSettingsForm
    success_url = reverse_lazy('mailsender:all_emailing')

    def form_valid(self, form):
        """заполнение поля владельца при валидации формы"""
        if form.is_valid():
            fields = form.save(commit=False)
            fields.created_by = self.request.user
        return super().form_valid(form)


class SetEmailingUpdateView(LoginRequiredMixin, CheckPermEditMixin, generic.UpdateView):
    model = my_models.SendSettings
    form_class = my_forms.SendSettingsForm
    success_url = reverse_lazy('mailsender:all_emailing')


class SetEmailingDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = my_models.SendSettings
    success_url = reverse_lazy('mailsender:all_emailing')
    extra_context = {
        'title': 'Удалить настройки рассылки'
    }

sender/templates/sender/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Sender{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossorigin="anonymous">
</head>
<style>
     /* Дополнительные стили */
     body {
         background-color: #f8f9fa;
         font-family: Arial, sans-serif;
     }
    .sidebar {
         height: 100vh;
         background-color: #343a40;
         color: white;
         padding: 20px;
     }
    .content {
         margin-top: 20px;
     }

     .card-img-top {
         width: 100%;
         height: 200px;
         object-fit: cover;
     }

     .card-title {
         margin-bottom: 10px;
     }

     .card-text {
         height: 60px;
         overflow: hidden;
     }
 </style>
<body>
<div class="d-flex flex-row">
    <!-- Sidebar -->
    {% include 'sender/includes/sidebar.html' %}

    <!-- Контент с карточками -->
    <div class="content container">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
        integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
        crossorigin="anonymous"></script>
</body>
</html>

sender/templates/sender/contentemail_confirm_delete.html
{% extends 'sender/base.html' %}
  {% block content %}

        <div class="container">

                <div class="">
                    <form method="post">
                        {% csrf_token %}

                        <h3>Вы уверены что хотите удалить шаблон "{{ object }}"?</h3>
                            <input type="submit" class="btn btn-lg btn-outline-danger" value="Удалить">
                            <a href="{% url 'mailsender:all_email_templates' %}" type="button" class="btn btn-lg btn-outline-warning">Вернуться</a>
                    </form>

                </div>

        </div>

        {% endblock %}

sender/templates/sender/contentemail_detail.html
{% extends 'sender/base.html' %}

  {% block content %}

      <div class="container">

          <div class="card-deck mb-12 text-center">

            <div class="card mb-4 box-shadow">


              <div class="card-body">
                <p>Тема письма: </p>
                <h5 class="">{{ object.headliner }} </h5>
                <p></p>
                <p>Текст письма:</p>
                <h5>{{ object.text }} </h5>
                <p></p>


               <a href="{% url 'mailsender:email_template_update' object.id %}" type="button" class="btn btn-lg btn-outline-warning">Редактировать</a>
               <a href="{% url 'mailsender:all_email_templates' %}" type="button" class="btn btn-lg btn-outline-primary">Вернуться</a>



              </div>

            </div>

          </div>

      </div>
  {% endblock %}

sender/templates/sender/contentemail_form.html
{% extends 'sender/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Добавить шаблон письма</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

sender/templates/sender/contentemail_list.html
{% extends 'sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Список шаблонов для рассылки</h1>
      <p class="lead">Тема и текст письма, доступные для рассылок</p>
    </div>


    <div class="container">
        <a href="{% url 'mailsender:email_template_create' %}" class="btn btn-lg btn-outline-primary">Добавить шаблон</a>
        <p></p>
        <div class="row">
            {% for item in object_list%}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">

                            <p class=""><b>Тема письма:</b></p>
                            <p class="">{{ item.headliner }}</p>
                            <p class=""><b>Текст письма:</b></p>
                            <p class="">{{ item.text   | slice:"0:100"}}</p>

                            <div class="row">
                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_template' item.id %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                                </div>

                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_template_delete' item.id %}"><button type="button" class="btn btn-outline-danger" >Удалить</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
  {% endblock %}

sender/templates/sender/customer_confirm_delete.html
{% extends 'sender/base.html' %}
  {% block content %}

        <div class="container">

                <div class="">
                    <form method="post">
                        {% csrf_token %}

                        <h3>Вы уверены что хотите удалить карточку клиента "{{ object }}"?</h3>
                            <input type="submit" class="btn btn-lg btn-outline-danger" value="Удалить">
                            <a href="{% url 'mailsender:all_customers' %}" type="button" class="btn btn-lg btn-outline-warning">Вернуться</a>
                    </form>

                </div>

        </div>

        {% endblock %}

sender/templates/sender/customer_detail.html
{% extends 'sender/base.html' %}

  {% block content %}

      <div class="container">

          <div class="card-deck mb-12 text-center">

            <div class="card mb-4 box-shadow">


              <div class="card-body">
                <p>Имя клиента: </p>
                <h5 class="">{{ object.full_name }} </h5>
                <p></p>
                <p>Электронная почта:</p>
                <h5>{{ object.email }} </h5>
                <p></p>
                <p>Комментарий:</p>
                <h5>{{ object.comment}} </h5>

               <a href="{% url 'mailsender:customer_update' object.id %}" type="button" class="btn btn-lg btn-outline-warning">Редактировать</a>
               <a href="{% url 'mailsender:all_customers' %}" type="button" class="btn btn-lg btn-outline-primary">Вернуться</a>



              </div>

            </div>

          </div>

      </div>
  {% endblock %}

sender/templates/sender/customer_form.html
{% extends 'sender/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Добавить клиента</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

sender/templates/sender/customer_list.html
{% extends 'sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Список клиентов для рассылки</h1>
      <p class="lead">Почтовые адреса и имена клиентов, которые подписаны на рассылку</p>
    </div>


    <div class="container">
        <a href="{% url 'mailsender:customer_create' %}" class="btn btn-lg btn-outline-primary">Добавить клиента</a>
        <p></p>
        <div class="row">
            {% for customer in object_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            {% if customer.full_name %}
                                <p class=""><b>Имя:</b> {{ customer.full_name }}</p>
                            {% else %}
                                <p class=""><b>Имя:</b> не указано</p>
                            {% endif %}
                            <p class=""><b>E-mail:</b> {{ customer.email }} </p>
                            <div class="row">
                                <div class="col-6">
                                    <a href="{% url 'mailsender:customer' customer.id %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                                </div>

                                <div class="col-6">
                                    <a href="{% url 'mailsender:customer_delete' customer.id %}"><button type="button" class="btn btn-outline-danger" >Удалить</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
  {% endblock %}

sender/templates/sender/home.html
{% extends 'sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Главная страница</h1>

    </div>


    <div class="container">
    <h3 class="text-center">Статистика текущих почтовых рассылок</h3>
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Кол-во подписчиков</h4>
                </div>
                <div class="card-body">
                    <h1 class="text-center">{{ customers.count }}</h1>
                    <a href="{% url 'mailsender:all_customers' %}"><button type="button" class="btn btn-outline-dark">Просмотр</button></a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Кол-во рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="text-center">{{ settings.count }}</h1>
                    <a href="{% url 'mailsender:all_emailing' %}"><button type="button" class="btn btn-outline-dark">Просмотр</button></a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Активные рассылки</h4>
                </div>
                <div class="card-body">
                    <h1 class="text-center">{{ act_settings.count}}</h1>
                    <a href="{% url 'mailsender:all_emailing' %}"><button type="button" class="btn btn-outline-dark">Просмотр</button></a>
                </div>
            </div>
        </div>
    </div>
</div>
  {% endblock %}

sender/templates/sender/sendsettings_confirm_delete.html
{% extends 'sender/base.html' %}
  {% block content %}

        <div class="container">

                <div class="">
                    <form method="post">
                        {% csrf_token %}

                        <h3>Вы уверены что хотите удалить рассылку "{{ object }}"?</h3>
                            <input type="submit" class="btn btn-lg btn-outline-danger" value="Удалить">
                            <a href="{% url 'mailsender:all_email_templates' %}" type="button" class="btn btn-lg btn-outline-warning">Вернуться</a>
                    </form>

                </div>

        </div>

        {% endblock %}

sender/templates/sender/sendsettings_detail.html
{% extends 'sender/base.html' %}

  {% block content %}

      <div class="container">

          <div class="card-deck mb-12 text-center">

            <div class="card mb-4 box-shadow">


              <div class="card-body">
                <p>Название рассылки: </p>
                <h5 class="">{{ object.name }} </h5>
                <p></p>
                <p>Время отправки:</p>
                <h5>{{ object.send_time }} </h5>
                <p></p>
                <p>Статус рассылки:</p>
                <h5>{{ object.get_status_display }} </h5>
                <p></p>
                <p>Периодичность отправки:</p>
                <h5>{{ object.get_period_display }} </h5>
                <p></p>
                <p>Список получателей:</p>
                  {% for customer in object.customer.all %}
                    <h5>{{ customer }} </h5>
                  {% endfor %}
                <p></p>


               <a href="{% url 'mailsender:email_setting_update' object.id %}" type="button" class="btn btn-lg btn-outline-warning">Редактировать</a>
               <a href="{% url 'mailsender:all_emailing' %}" type="button" class="btn btn-lg btn-outline-primary">Вернуться</a>



              </div>

            </div>

          </div>

      </div>
  {% endblock %}

sender/templates/sender/sendsettings_form.html
{% extends 'sender/base.html' %}

{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3>Добавить рассылку</h3>
                    </div>
                    <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </form>
    </div>
{% endblock %}

sender/templates/sender/sendsettings_list.html
{% extends 'sender/base.html' %}

  {% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="">Список рассылок</h1>
      <p class="lead">Настройки доступных рассылок</p>
    </div>


    <div class="container">
        <a href="{% url 'mailsender:email_setting_create' %}" class="btn btn-lg btn-outline-primary">Добавить рассылку</a>
        <p></p>
        <div class="row">
            {% for item in object_list%}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">

                            <p class=""><b>Название рассылки:</b></p>
                            <p class="">{{ item.name }}</p>
                            <p class=""><b>Тема письма:</b></p>
                            <p class="">{{ item.message }}</p>
                            <p class=""><b>Статус рассылки:</b></p>
                            <p class="">{{ item.get_status_display }}</p>
                            <p class=""><b>Периодичность рассылки:</b></p>
                            <p class="">{{ item.get_period_display }}</p>

                            <div class="row">
                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_setting' item.id %}"><button type="button" class="btn btn-outline-dark" >Просмотр</button></a>
                                </div>

                                <div class="col-6">
                                    <a href="{% url 'mailsender:email_setting_delete' item.id %}"><button type="button" class="btn btn-outline-danger" >Удалить</button></a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
      </div>
  {% endblock %}